[ {
	"id" :"5c919ee03772a0f50137731a772f9923",
	"text" :"全网监视",
	"root" :false,
	"icon" :"resources/images/menustore/area.png",
	"smallIcon" :"resources/images/smallmenustore/area.png",
	"cntType" :"globaltopo",
	"size" :-1,
	"shortCut" :1,
	"quickStart" :1,
	"mode" :0,
	"pid" :null,
	"pName" :null,
	"sort" :0,
	"menuModel" :null,
	"pname" :null,
	"menu" :null
}, {
	"id" :"5c919ee03772a0f50137731a772f9922",
	"text" :"拓扑监测",
	"root" :false,
	"icon" :"resources/images/menustore/config.png",
	"smallIcon" :"resources/images/smallmenustore/config.png",
	"cntType" :"gistopo",
	"size" :-1,
	"shortCut" :1,
	"quickStart" :1,
	"mode" :0,
	"pid" :null,
	"pName" :null,
	"sort" :0,
	"menuModel" :null,
	"pname" :null,
	"menu" :null
}, {
	"id" :"5c919ee03772a0f50137731a772f9924",
	"text" :"物理拓扑",
	"root" :false,
	"icon" :"resources/images/menustore/topocfg.png",
	"smallIcon" :"resources/images/smallmenustore/topocfg.png",
	"cntType" :"topoconfiggraph",
	"size" :800,
	"shortCut" :1,
	"quickStart" :1,
	"mode" :0,
	"pid" :null,
	"pName" :null,
	"sort" :0,
	"menuModel" :null,
	"pname" :null,
	"menu" :null
}, {
	"id" :"5c919ee03772a0f50137731a772f9925",
	"text" :"系统监视",
	"root" :false,
	"icon" :"resources/images/menustore/faultstatistic.png",
	"smallIcon" :"resources/images/smallmenustore/faultstatistic.png",
	"cntType" :"systemstatus",
	"size" :800,
	"shortCut" :1,
	"quickStart" :1,
	"mode" :0,
	"pid" :null,
	"pName" :null,
	"sort" :0,
	"menuModel" :null,
	"pname" :null,
	"menu" :null
}, {
	"id" :"5c919ee03772a0f50137731acaf12301",
	"text" :"设备配置",
	"root" :false,
	"icon" :"resources/images/menustore/cmdterminal.png",
	"smallIcon" :"resources/images/smallmenustore/cmdterminal.png",
	"cntType" :"devframeconfigview",
	"size" :800,
	"shortCut" :1,
	"quickStart" :1,
	"mode" :0,
	"pid" :null,
	"pName" :null,
	"sort" :0,
	"menuModel" :null,
	"pname" :null,
	"menu" :null
}, {
	"id" :"5c919ee03772a0f50137731acaf2200",
	"text" :"故障统计",
	"root" :false,
	"icon" :"resources/images/menustore/faulthistroy.png",
	"smallIcon" :"resources/images/smallmenustore/faulthistroy.png",
	"cntType" :"panel",
	"size" :800,
	"shortCut" :1,
	"quickStart" :1,
	"mode" :0,
	"pid" :null,
	"pName" :null,
	"sort" :0,
	"menuModel" :null,
	"pname" :null,
	"menu" :null
}, {
	"id" :"5c919ee03772a0f50137731acaf33300",
	"text" :"任务管理",
	"root" :false,
	"icon" :"resources/images/menustore/buildstrategy.png",
	"smallIcon" :"resources/images/smallmenustore/buildstrategy.png",
	"cntType" :"panel",
	"size" :800,
	"shortCut" :1,
	"quickStart" :1,
	"mode" :0,
	"pid" :null,
	"pName" :null,
	"sort" :0,
	"menuModel" :null,
	"pname" :null,
	"menu" :null
}, {
	"id" :"5c919ee03772a0f50137731acaf32117",
	"text" :"用户管理",
	"root" :false,
	"icon" :"resources/images/menustore/system.png",
	"smallIcon" :"resources/images/smallmenustore/system.png",
	"cntType" :"userlist",
	"size" :800,
	"shortCut" :1,
	"quickStart" :1,
	"mode" :0,
	"pid" :null,
	"pName" :null,
	"sort" :0,
	"menuModel" :null,
	"pname" :null,
	"menu" :null
}, {
	"id" :"5c919ee03772a0f50137731acaf32118",
	"text" :"权限组管理",
	"root" :false,
	"icon" :"resources/images/menustore/usergroup.gif",
	"smallIcon" :"resources/images/smallmenustore/usergroup.gif",
	"cntType" :"usergroup",
	"size" :800,
	"shortCut" :1,
	"quickStart" :1,
	"mode" :0,
	"pid" :null,
	"pName" :null,
	"sort" :0,
	"menuModel" :null,
	"pname" :null,
	"menu" :null
}, {
	"id" :"5c919ee03772a0f50137731a772f9992",
	"text" :"菜单管理",
	"root" :false,
	"icon" :"resources/images/menustore/menu.png",
	"smallIcon" :"resources/images/smallmenustore/menu.png",
	"cntType" :"menulist",
	"size" :-1,
	"shortCut" :1,
	"quickStart" :1,
	"mode" :0,
	"pid" :null,
	"pName" :null,
	"sort" :0,
	"menuModel" :null,
	"pname" :null,
	"menu" :null
}, {
	"id" :"5c919ee03772a0f50137731a772f9991",
	"text" :"数据管理",
	"root" :false,
	"icon" :"resources/images/menustore/log.png",
	"smallIcon" :"resources/images/smallmenustore/log.png",
	"cntType" :"sysparam",
	"size" :800,
	"shortCut" :1,
	"quickStart" :1,
	"mode" :0,
	"pid" :null,
	"pName" :null,
	"sort" :0,
	"menuModel" :null,
	"pname" :null,
	"menu" :null
} ]